### ISSUE TITLE
Architecture/Direction

### ISSUE THREAD

**Issue by technosailor** [sc0ttkclark/wordpress-fields-api#46]
As we are dealing with some moving pieces, regarding shared architectures, classes/subclasses, etc. This issue is for deciding and implementing these structures.

@sc0ttkclark: Some initial thoughts based on your recent work of Jan 27th, 2016.

Here is my feedback, by request. Some of it may seem obvious, but I'm approaching this from the perspective of not being overly familiar with the code and philosophy and what I, as an arbitrary plugin developer, would need to get up to speed and implement it.

### [Creating an implementation class](https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/docs/creating-an-implementation.md)

- How is $this->object_type defined?
- Does obejct_type mirror WordPress object types (i.e. WP_User, WP_Post, etc)?
- Does object_name mirror WordPress object names (i.e. post_tag, etc )?
- Maybe we should force the use of WP_Error returns on save if failed?

### Registering Screen

- For plugins, how does registering a screen differ from hooking to admin_menu and a callback in the traditional plugin development sense?

### General

- I feel like there is some need for some terminology definition here. You allude to what a Screen and a Control is, but how they relate to WordPress is mildly unclear (though probably a bit more clear to me). If a WordPress developer jumped into this, it would take a bit just to understand the terminology and how it relates to what they already know in WordPress. For example...
 - What is a screen? Is it an admin page? Is it a customizer section? Do the terminologies match what is already in WordPress?
 - What is a panel and how is it different from a screen?
 - Are there specific use cases that can be pointed to in the WP Admin that would make this stuff clearer? Not to dumb things down for a fairly advanced project, but... Maybe some screenshots lining up what belongs to what in the Fields implementation?

- Do plugin authors have to hook on admin_init for saving callbacks? I'd assume yes, but that's not clear.
- [Why is the object_name null here? Why wouldn't it be 'user'?](https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/docs/examples/user/address.php#L13)

**Comment by sc0ttkclark** [comment]
Some actionable todos from this feedback:

- [ ] Document what Object Types are (`docs/what-are-object-types-and-object-names.md`)
- [ ] Document what Object Names are (`docs/what-are-object-types-and-object-names.md`)

And some responses (some of which solve todos above but still need to make their way into the docs --

## Object Types

Object Types include:

* `user` (WP_User)
* `post` (WP_Post)
* `term` (WP_Term)
* `comment` (WP_Comment)
* `settings` (Settings API)
* `customizer` (Customizer API)
* Support for custom object types is baked in through hooks

## Object Names

Object Names apply only to:

* `post` (Post Types: `post`, `page`, `your_cpt`)
* `term` (Taxonomies: `category`, `post_tag`, `your_ct`)
* `comment` (Comment Types: `comment`, `ping`, `your_cct`)

Object types that do not need an object name include:

* `user`
* `settings`
* `customizer`

Use of object names can be used by custom object types at their discretion.

### Default Object Names and Handling

The default object name is based on the object type, it adds an underscore to the object type -- `_{$object_type}`

When no object name is provided (or it matches the default object name) then those screens/sections/controls/fields apply to all object names for an object type and will be inherited.

An example of that can be seen in the `WP_Fields_API_Screen_Term` implementation class, which adds the term `name`, `slug`, `parent`, and `description` fields to *all* taxonomies. Visibility ultimately rests with the section or control capabilities callback, which can further limit access to a specific section or control and prevent them from being viewed/used.

**Comment by sc0ttkclark** [comment]
Now some answers:

### [Creating an implementation class](https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/docs/creating-an-implementation.md)

- How is $this->object_type defined? **See previous comment**
- Does obejct_type mirror WordPress object types (i.e. WP_User, WP_Post, etc)? **See previous comment**
- Does object_name mirror WordPress object names (i.e. post_tag, etc )? **See previous comment**
- Maybe we should force the use of WP_Error returns on save if failed? **Yes, that's part of what I was working on this week.**

### Registering Screen

- For plugins, how does registering a screen differ from hooking to admin_menu and a callback in the traditional plugin development sense?  **Registering Screens does not add Admin UI for you, that still needs to be done with admin_menu and the associated page callback, which you then follow the implementation documentation for rendering the screen form and handline saving.**

### General

- I feel like there is some need for some terminology definition here. You allude to what a Screen and a Control is, but how they relate to WordPress is mildly unclear (though probably a bit more clear to me). If a WordPress developer jumped into this, it would take a bit just to understand the terminology and how it relates to what they already know in WordPress. For example... **We've been chatting about possibly changing the terminology of "Screen" to "Form" so it would be `WP_Fields_API_Form` instead of ``WP_Fields_API_Screen`**
 - What is a screen? Is it an admin page? Is it a customizer section? Do the terminologies match what is already in WordPress? **A screen is a collection of Sections and Controls for organized display in a form, see above item as we could improve terminology**
 - What is a panel and how is it different from a screen? **Screens are what Panels are in the Customizer, they have the same functionality except the Fields API has some new functionality added to make it easier for our implementations in WP Core**
 - Are there specific use cases that can be pointed to in the WP Admin that would make this stuff clearer?  Not to dumb things down for a fairly advanced project, but... Maybe some screenshots lining up what belongs to what in the Fields implementation? **We definitely need screenshots, going to add this to the todos list, we should include a screenshot breakdown in the User profile for instance, with colored boxes that explain the terminology visually**
- Do plugin authors have to hook on admin_init for saving callbacks? I'd assume yes, but that's not clear. **Yes, that's still necessary as a Screen can be used anywhere, it just needs to be called**
- [Why is the object_name null here? Why wouldn't it be 'user'?](https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/docs/examples/user/address.php#L13) **Expalined in the previous comment about Default Object Names**

**Comment by sc0ttkclark** [comment]
Added new documentation via #22, added those to README.md, and "Screens" are now "Forms" to make things much more clear.
