### ISSUE TITLE
Repeatable fields / Groups

### ISSUE THREAD

**Issue by KingYes** [sc0ttkclark/wordpress-fields-api#8]
Like from ACF project: http://www.advancedcustomfields.com/resources/repeater/

**Comment by ihorvorotnov** [comment]
A huge +1 on this. I've purchased ACF 5 Pro because of this field (and flexible). One note - this repeater should be able to hold a separate "section" (a set of fields), like the one from ACF. Otherwise it's not that powerful.

**Comment by swissspidy** [comment]
I think the API should only offer a standard set of fields, just like the customiser. A repeatable field could be plugin material.

**Comment by vinkla** [comment]
I'm with @KingYes on this one! This is the number one feature in ACF.

**Comment by helenhousandi** [comment]
This is largely a UI concern, and I would agree that this is largely plugin or custom implementation material. I've built a number of repeatable field implementations, and each one is a little bit different both in terms of UI and in terms of storage, especially across different contexts (posts vs. users, for instance). Making repeatable UI generic to various contexts, containers, and field sets in a generalized core fashion is a never-ending hole, based on my past experiences. In any case, let's get through working on the API side of things, with this in mind wherever considerations might need to be made, and revisit later.

**Comment by sc0ttkclark** [comment]
Sounds good to me, it would be great to free people of the burden of loop field fragmentation of storage and usage (and cost in some cases) -- but I know also from my experience (and from seeing @helenhousandi's experience first-hand) that loop fields are anything but simple / generic from project to project.

**Comment by grantpalin** [comment]
I'm as interested in repeatable fields as much as the next person, but I also agree that the base API should support simple fields, and more complex (and out of the norm) fields should be provided through additional plugins.

**Comment by jawittdesigns** [comment]
Yeah, but if you leave repeatable fields for plugins won't that defeat the point of main goal of the API? The repeater it self can be thought of as a field. Sure the basic fields will be supported, but then there  would be hundreds of different repeater fields as plugins. 

I use ACF and CMB and the repeaters are the fields I use the most. I use it more that radio and checkboxes combined. Like @sc0ttkclark said they're difficult, and that's why I use ACF and CMB. I'd hope this project would free me from having to use third party code, but if a repeater isn't included, the API would be useless for me. I'll still just use third party stuff.

**Comment by helenhousandi** [comment]
And your "third party stuff" will use the underlying API to build that UI for you. There is no single generic repeatable field UI as far as I have ever seen, only sites and users that deal with UI that hasn't been tailored to them because some library was used. Either way, this project is still in the PHP API design and implementation phase, not complex UI consideration.

**Comment by jawittdesigns** [comment]
That's about what I figured someone would say, but hey it was worth a shot even thought I knew it was futile. The decision has been made a no amount of discussion will change the core team's mind. The opinion of the WordPress community used to matter. I wonder what happened?

**Comment by helenhousandi** [comment]
There has been no definitive decision made - I am saying it is too early to make one.

**Comment by jawittdesigns** [comment]
Sure it has, it was decided with the customizer like @swissspidy said. 

It just sad that it's "The WordPress Way" or the highway, now. 

You don't need a UI to set up repeatable fields. Just the functionality. Id the image uploader going to be excluded? That needs a UI, too. 

No, the decision's been made, and there's no fighting it.

It just bums me out that WordPress has become this way.

**Comment by helenhousandi** [comment]
I am going to respond to the above and then close and lock this issue until further notice, because this is not productive.

Wherever the PHP API ends up, it will not prevent data from stored or retrieved. A repeatable field is just data at the end of the day - the only thing that makes it repeatable is the UI. Even its storage can be variable, and that's the one related piece we should think about at this stage, which is how decisions are made and flexibility granted when it comes to data storage. This project is not dealing with any UI **right now** - it will eventually, but it is not at that stage yet. I understand that API and UI are not always easily conceptually separated, and often exist entangled, but let's stay on track, please.

**Comment by helenhousandi** [comment]
Oh, turns out I can lock without closing. Reopening so we don't forget, then. :)

**Comment by sc0ttkclark** [comment]
As #30 is now resolved and closed, this issue is not held back in any way other than we're not focusing on it for the initial core proposal. If anyone is interested in getting a prototype of this rolling, I'll certainly help enable you, but for now we'll leave this as closed.

**Comment by sc0ttkclark** [comment]
#61
