### ISSUE TITLE
`registering-fields.md` is out of date

### ISSUE THREAD

**Issue by citelao** [sc0ttkclark/wordpress-fields-api#86]
I'm reading through the [Registering Fields section](https://github.com/sc0ttkclark/wordpress-fields-api/blob/develop/docs/registering-fields.md#registering-fields-and-control), and it seems like the documentation is out of sync with the API.

- **Registering Sections** documents non-existent method `$wp_fields->add_section()`
- **Registering Controls** documents non-existent method `$wp_fields->add_control()`
- **Registering Fields (and Control)** documents a method for adding controls to a field that also no longer exists.

As I understand it, the API changed at some point to only allow top-down specification; e.g. from a form you can create sections, from sections you can create controls, and from controls you can create fields. The singleton now only lets you create forms and fields; anything else must be done within that order.

Is this correct?

The relevant code, under **Registering Fields (and Control)**:

```
// Section ID
$section_id = 'my-section'; // @todo Fill in section ID

// Field ID and options
$field_id = 'my-field'; // @todo Fill in field ID
$field_args = array(
    // You can register a control for this field at the same time
    'control' => array(
        // Control ID defaults to the same as the Field ID
        'type'        => 'text', // @todo Change control type if needed
        'section'     => $section_id,
        'label'       => __( 'My Field', 'my-text-domain' ), // @todo Fill in label, update text domain
        'description' => __( 'Description of My Field', 'my-text-domain' ), // @todo Fill in description, update text domain
    ),
);

// Register field (and control)
$wp_fields->add_field( $field_id, $field_args );
```

**Comment by lukecarbis** [comment]
This also affects the current "API Examples" included in the `docs/examples` directory.

On `develop`, an example option form tries to do `$wp_fields->add_section`, but this creates a fatal error, since the `add_section` method no longer exists inside `WP_Fields_API` class (only in `WP_Fields_API_Form`:
https://github.com/sc0ttkclark/wordpress-fields-api/blob/24c900112b91d908632f331b85e46a7ed2f115a8/docs/examples/option/_starter.php#L34

To work, the result of `$wp_fields->add_form` should be stored (like in a `$form` variable) and then the section added to that result (`$form->add_section`).
